### ISSUE TITLE
Updating PyPi with a newer version

### ISSUE THREAD

**Issue by AlmogCohen** [armooo/suds_requests#10]
Great package you've got here! Thanks!

The code on PyPi seems a bit old (from Jan). I like some of the upgrades to the code, including the python 3 support and the usage of the better `suds-jurko` package. Can you push a newer version to PyPi please?

**Comment by AlmogCohen** [comment]
I think it would also make your PyPi version compatible with python 3...which is nice :)

**Comment by armooo** [comment]
A new version based on master has been uploaded to pypi.

**Comment by AlmogCohen** [comment]
Are you amazing or what? :) Thanks!!!!
