### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ricardolopezgr** [armooo/suds_requests#12]
Hello,

I'm having this issue to install the package

![image](https://user-images.githubusercontent.com/36821909/152137500-ea3d35df-5eb2-412f-9a29-cf1519b2f9b2.png)

Packages SUDS and requests are installed, thanks in advance!

**Comment by armooo** [comment]
It looks like suds-jurko uses 2to3 for python3 support, but support for it
has been removed from setuptools.
https://setuptools.pypa.io/en/latest/history.html#v58-0-0
-- jason

**Comment by ricardolopezgr** [comment]
Hi @armooo 

Thanks for the reply, downgrading `setuptools` makes the trick!
